import { useEffect, useState } from "react";

export function useCount() {
	const [count, setCount] = useState(null);

	const fetchCount = async () => {
		const res = await fetch("/api/count");
		const data = await res.json();
		console.log("Total number of notes generated by Billions of Notes:", data);
		setCount(data.count);
	};

	const incrementCount = async (incrementValue) => {
		await fetch("/api/count", {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({ incrementValue }),
		});

		fetchCount();
	};

	useEffect(() => {
		fetchCount();
	}, []);

	return { count, incrementCount };
}
